/**
 * PURE Network-Game-panel view-model (issue #13 / #16 — the game-code combobox). The companion DOM
 * glue is `netPanel.ts` (the drawer panel wiring Host/Join to the existing
 * `hostGame`/`joinGame`/`setPendingJoinCode` seams). Simplified picker (issue #16):
 *
 *   Flow = ONE combobox — a text input plus a dropdown of recently-used codes — feeding a Host
 *   button (create this room) and a Join button (enter this room). One code, two actions.
 *     - The input's PLACEHOLDER is a fresh random code, generated (via `generateGameCode`) when the
 *       panel OPENS and passed into this model (the glue owns the randomness; this stays pure).
 *     - The EFFECTIVE code = the typed text (trimmed) when non-empty, else the placeholder — so a
 *       Host/Join with an untouched input uses the offered random code, and typing overrides it.
 *     - The DROPDOWN lists the recent codes (newest-first from the C.1 store); clicking one fills the
 *       input, and each row has a remove control that drops just that code from the store.
 *
 * This module owns the PURE decisions the panel makes: what the EFFECTIVE code is, whether it is
 * {@link validateGameCode}-valid (so Host / Join are enabled), the human error for an invalid TYPED
 * code, and the canonical code the widget stashes/records. Turning the combobox state + the recent-
 * codes list into the serializable model the DOM renders is DOM-free and deterministic, so it earns
 * the strict unit + mutation gate exactly as {@link ./netModel.ts} does. Validation reuses the SAME
 * `validateGameCode` the join path uses, so the panel can never enable Host/Join for a code the
 * transport would then reject. The placeholder is always valid by construction (it comes from
 * `generateGameCode`), so an empty input always leaves the buttons enabled.
 */

import { validateGameCode, type CodeError, CODE_ERROR_TEXT } from './netModel.ts';

/**
 * The combobox's editable state — the single source of truth the DOM reflects and the pure mutations
 * below transform. `text` is the raw typed input (any case / whitespace; validated on derive);
 * `placeholder` is the fresh random code offered when the panel opened (shown greyed as the input's
 * HTML placeholder, NOT its value); `recent` is the recent-codes list from the C.1 store (newest-
 * first, canonical). The EFFECTIVE code is DERIVED from `text` + `placeholder` by
 * {@link deriveNetPanel}, never stored separately.
 */
export interface NetPanelState {
  /** The raw text typed in the combobox input (any case / whitespace; validated on derive). */
  readonly text: string;
  /** The fresh random code offered when the panel opened — shown as the input's placeholder. */
  readonly placeholder: string;
  /** The recent codes to list in the dropdown, newest-first + canonical (from the C.1 store). */
  readonly recent: readonly string[];
}

/**
 * The initial combobox state for a freshly-opened panel: the given fresh random `placeholder` and
 * the given `recent` list, with an empty typed input (so Host/Join default to the placeholder). The
 * `placeholder` is generated by the glue via `generateGameCode` and passed in — the randomness stays
 * out of this pure module.
 *
 * @param placeholder The fresh random code to offer as the input's placeholder.
 * @param recent The recent codes (newest-first, canonical) from the C.1 store.
 */
export function initialNetPanel(
  placeholder: string,
  recent: readonly string[],
): NetPanelState {
  return { text: '', placeholder, recent };
}

/** Set the typed text (pure, immutable). Leaves the placeholder + recent list untouched. */
export function setPanelText(state: NetPanelState, text: string): NetPanelState {
  return { ...state, text };
}

/**
 * Fill the input from a chosen recent code (pure). Clicking a dropdown row copies its code into the
 * typed text so it becomes the effective code (and can then be edited); it is just a targeted
 * {@link setPanelText}, named for the call site's intent.
 */
export function chooseRecent(state: NetPanelState, code: string): NetPanelState {
  return setPanelText(state, code);
}

/**
 * Remove exactly one code from the recent list (pure, immutable). Drops every entry equal to `code`
 * (the store is deduped, so at most one matches) and leaves the rest in order; the typed text +
 * placeholder are untouched. The glue also removes it from the C.1 store; this keeps the rendered
 * model in sync without a re-read.
 */
export function removeRecent(state: NetPanelState, code: string): NetPanelState {
  return { ...state, recent: state.recent.filter((c) => c !== code) };
}

/** A recent-code row the dropdown renders (its code; newest-first order comes from the store). */
export interface NetPanelRecentRow {
  /** The canonical recent code. */
  readonly code: string;
}

/** The serializable Network-Game-panel view-model the DOM renders (and Playwright asserts on). */
export interface NetPanelModel {
  /** The raw typed text to show in the combobox input. */
  readonly text: string;
  /** The placeholder (fresh random code) to show greyed in the empty input. */
  readonly placeholder: string;
  /** The dropdown rows (recent codes, newest-first). */
  readonly recentRows: readonly NetPanelRecentRow[];
  /**
   * The EFFECTIVE code Host/Join act on: the trimmed typed text when non-empty, else the placeholder.
   * Never empty in practice (the placeholder is always a valid generated code), so an untouched input
   * hosts/joins the offered random room.
   */
  readonly effectiveCode: string;
  /**
   * The CANONICAL (trimmed, upper-cased) effective code when it validates, or `null` when it does
   * not — exactly what the widget stashes via `setPendingJoinCode` and records into the C.1 store, so
   * the panel never hands a malformed code to the transport or the store.
   */
  readonly canonicalCode: string | null;
  /** Whether the effective code validates (so Host + Join are enabled). */
  readonly codeValid: boolean;
  /**
   * The human error for the TYPED code when it is invalid, or `null` when valid. Reuses the SAME
   * {@link CODE_ERROR_TEXT} labels the inline join validation uses (SSOT). Only a non-empty typed
   * code can be invalid — an empty input falls back to the always-valid placeholder, so there is no
   * error to show then.
   */
  readonly codeError: string | null;
}

/**
 * Derive the {@link NetPanelModel} from the combobox {@link NetPanelState}. Pure and deterministic:
 *   - **effectiveCode** — `state.text.trim()` when non-empty, else `state.placeholder`. So an
 *     untouched input uses the offered random code; typing overrides it.
 *   - **canonicalCode / codeValid / codeError** — run the effective code through the SAME
 *     {@link validateGameCode} the join path uses. A valid code yields its canonical form and enables
 *     the buttons; an invalid one yields `null` + the human reason and disables them. The placeholder
 *     is valid by construction, so only a bad TYPED code can disable the buttons.
 *   - **recentRows** — the recent codes verbatim (already newest-first, deduped, canonical from the
 *     C.1 store), one row each for the dropdown.
 *
 * @param state The combobox state.
 * @returns The serializable model the DOM renders.
 */
export function deriveNetPanel(state: NetPanelState): NetPanelModel {
  const typed = state.text.trim();
  const effectiveCode = typed !== '' ? typed : state.placeholder;

  const validation = validateGameCode(effectiveCode);
  const codeValid = validation.ok;
  const canonicalCode = validation.ok ? validation.code : null;
  const codeError = validation.ok ? null : codeErrorText(validation.reason);

  const recentRows: NetPanelRecentRow[] = state.recent.map((code) => ({ code }));

  return {
    text: state.text,
    placeholder: state.placeholder,
    recentRows,
    effectiveCode,
    canonicalCode,
    codeValid,
    codeError,
  };
}

/** Map a validation reason to its human label (SSOT: the same table the inline join error uses). */
function codeErrorText(reason: CodeError): string {
  return CODE_ERROR_TEXT[reason];
}
